"""association payment subscribe

Revision ID: 6321110dd668
Revises: ce9c26fbcf6a
Create Date: 2025-04-10 11:45:30.560352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6321110dd668'
down_revision: Union[str, None] = 'ce9c26fbcf6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('subscription_id', sa.String(), nullable=True))
    op.alter_column('payments', 'article_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_foreign_key(None, 'payments', 'subscriptions', ['subscription_id'], ['id'], ondelete='CASCADE')
    op.drop_column('sliding_scale_tariffs', 'status')
    op.drop_column('subscriptions', 'status')
    op.drop_column('volume_discounts', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('volume_discounts', sa.Column('status', postgresql.ENUM('ACTIF', 'INACTIF', name='statusproposition'), autoincrement=False, nullable=False))
    op.add_column('subscriptions', sa.Column('status', postgresql.ENUM('ACTIF', 'INACTIF', name='statusproposition'), autoincrement=False, nullable=False))
    op.add_column('sliding_scale_tariffs', sa.Column('status', postgresql.ENUM('ACTIF', 'INACTIF', name='statusproposition'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.alter_column('payments', 'article_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('payments', 'subscription_id')
    # ### end Alembic commands ###
