"""remove single constraint number payment

Revision ID: 84bccd78b331
Revises: fa8a6e020a43
Create Date: 2025-04-25 15:59:57.014734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84bccd78b331'
down_revision: Union[str, None] = 'fa8a6e020a43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('payments_payment_number_key', 'payments', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('payments_payment_number_key', 'payments', ['payment_number'])
    # ### end Alembic commands ###
