"""amount to paynumber of articles published

Revision ID: 8564adac6373
Revises: 6321110dd668
Create Date: 2025-04-16 15:10:08.955035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8564adac6373'
down_revision: Union[str, None] = '6321110dd668'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('start_date', sa.Date(), nullable=True))
    op.add_column('articles', sa.Column('amount_to_pay', sa.Float(), nullable=True))
    op.drop_column('articles', 'daily_rate')
    op.alter_column('payments', 'payment_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('tax_intervals', 'min_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('tax_intervals', 'max_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('tax_intervals', 'daily_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.drop_column('tax_intervals', 'is_read')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tax_intervals', sa.Column('is_read', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.alter_column('tax_intervals', 'daily_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('tax_intervals', 'max_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('tax_intervals', 'min_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('payments', 'payment_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('articles', sa.Column('daily_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('articles', 'amount_to_pay')
    op.drop_column('articles', 'start_date')
    # ### end Alembic commands ###
