"""association user subscribe

Revision ID: ce9c26fbcf6a
Revises: 3ec85ffeede1
Create Date: 2025-04-07 14:19:03.892832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce9c26fbcf6a'
down_revision: Union[str, None] = '3ec85ffeede1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('subscription_id', sa.String(), nullable=True))
    op.alter_column('articles', 'owner_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_foreign_key(None, 'articles', 'subscriptions', ['subscription_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'articles', type_='foreignkey')
    op.alter_column('articles', 'owner_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('articles', 'subscription_id')
    # ### end Alembic commands ###
