"""Add notification for subscription

Revision ID: fa8a6e020a43
Revises: a973cf8ecfdd
Create Date: 2025-04-25 14:41:16.064630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa8a6e020a43'
down_revision: Union[str, None] = 'a973cf8ecfdd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('subscription_id', sa.String(), nullable=True))
    op.alter_column('notifications', 'article_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_foreign_key(None, 'notifications', 'subscriptions', ['subscription_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.alter_column('notifications', 'article_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('notifications', 'subscription_id')
    # ### end Alembic commands ###
